package presentation;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.Calendar;
import java.util.StringTokenizer;

/**
 * 634.1 Programmation - TP P01
 * 
 * Fenêtre de saisie d'un nouvel employé:
 * - Singleton
 * 
 * @author lopesmagalhaesfrederic
 * @version 1.0
 */
public class FrmNouveau extends java.awt.Frame {
  
  private static FrmNouveau fm = null;
  private static String 
          DATE_PATTERN = "yyyy.MM.dd",
          SEP_PATTERN = "/";
  private FrmMain fmMere;
  
  private Date d;
  
  /* Constructeur */
  private FrmNouveau (FrmMain fmMere) {
    initComponents();
    this.fmMere = fmMere;
    initChoices();
  } // Constructeur
  
  public static FrmNouveau getInstance(FrmMain fmMere) {
    if(fm==null) {fm=new FrmNouveau(fmMere);}
    return fm;
  }
  
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    java.awt.Label label1 = new java.awt.Label();
    tfNom = new java.awt.TextField();
    java.awt.Label label2 = new java.awt.Label();
    tfPrenom = new java.awt.TextField();
    lblDateEngagement = new java.awt.Label();
    tfDateEngagement = new java.awt.TextField();
    java.awt.Label label4 = new java.awt.Label();
    chFonctions = new java.awt.Choice();
    java.awt.Label label5 = new java.awt.Label();
    chDepartements = new java.awt.Choice();
    btnEnregistrer = new java.awt.Button();

    setResizable(false);
    setTitle("Saisie d'un employé");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    label1.setText("Nom");

    tfNom.addTextListener(new java.awt.event.TextListener() {
      public void textValueChanged(java.awt.event.TextEvent evt) {
        verifierDonnees(evt);
      }
    });

    label2.setText("Prénom");

    tfPrenom.addTextListener(new java.awt.event.TextListener() {
      public void textValueChanged(java.awt.event.TextEvent evt) {
        verifierDonnees(evt);
      }
    });

    lblDateEngagement.setText("Date d'engagement");

    tfDateEngagement.setText("yyyy.MM.dd");
    tfDateEngagement.addTextListener(new java.awt.event.TextListener() {
      public void textValueChanged(java.awt.event.TextEvent evt) {
        verifierDonnees(evt);
      }
    });

    label4.setText("Fonction");

    label5.setText("Département");

    btnEnregistrer.setEnabled(false);
    btnEnregistrer.setLabel("Enregistrer");
    btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEnregistrerActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(74, 74, 74)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(tfNom, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
              .addComponent(tfPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblDateEngagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(tfDateEngagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(chFonctions, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
              .addComponent(chDepartements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnEnregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblDateEngagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tfDateEngagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(chFonctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(chDepartements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(23, 23, 23)
        .addComponent(btnEnregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    dispose();
  }//GEN-LAST:event_formWindowClosing

  private boolean isDateValid(String dateToValidate, String pattern) {
    if(dateToValidate.length()<10) {
      return false;
    }
    SimpleDateFormat sdf = new SimpleDateFormat(pattern);
    java.util.Date date;
    try {
      date = sdf.parse(dateToValidate);
    } catch (Exception e) {
      return false;
    }
    if (date.after(Calendar.getInstance().getTime())) {
      return false;
    }
    StringTokenizer stDate = new StringTokenizer(dateToValidate, ".");
    d = new Date(date.getTime());
    return true;
  } // isDateValid
  
  private void verifierDonnees(java.awt.event.TextEvent evt) {//GEN-FIRST:event_verifierDonnees
    btnEnregistrer.setEnabled(false);
    if(!tfDateEngagement.getText().trim().isEmpty()) {
      if(isDateValid(tfDateEngagement.getText().trim(), DATE_PATTERN)) {
        tfDateEngagement.setForeground(Color.black);
        if(!tfNom.getText().trim().isEmpty() 
            && !tfPrenom.getText().trim().isEmpty()) {
          btnEnregistrer.setEnabled(true);
        }
      } else {
        tfDateEngagement.setForeground(Color.red);
      }
    }
  }//GEN-LAST:event_verifierDonnees

  private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
    fmMere.addEmploye(tfNom.getText().trim(), tfPrenom.getText().trim(),
            chFonctions.getSelectedIndex(), d, chDepartements.getSelectedIndex());
    initFrame();
    dispose();
  }//GEN-LAST:event_btnEnregistrerActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.Button btnEnregistrer;
  private java.awt.Choice chDepartements;
  private java.awt.Choice chFonctions;
  private java.awt.Label lblDateEngagement;
  private java.awt.TextField tfDateEngagement;
  private java.awt.TextField tfNom;
  private java.awt.TextField tfPrenom;
  // End of variables declaration//GEN-END:variables

  private void initFrame() {
    tfDateEngagement.setText("");
    tfNom.setText("");
    tfPrenom.setText("");
    chDepartements.select(0);
    chFonctions.select(0);
    d = null;
  } // initFrame

  private void fillChoice(java.awt.Choice c, String[] array) {
    for(int i=0; i<array.length; i++) {
      c.add(array[i]);
    }
  } // fillChoice
  
  private void initChoices() {
    fillChoice(chDepartements, fmMere.getArrayDepartements());
    fillChoice(chFonctions, fmMere.getArrayFonctions());
  } // initChoices
  
} // FrmNouveau
